"""latest revisions

Revision ID: 4fb9b9e0dc81
Revises: 142d1c0323a5
Create Date: 2022-10-25 04:39:15.428505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb9b9e0dc81'
down_revision = '142d1c0323a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_blacklisted_tokens_id'), 'users_blacklisted_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_blacklisted_tokens_id'), table_name='users_blacklisted_tokens')
    op.drop_table('users_blacklisted_tokens')
    # ### end Alembic commands ###
