"""latest revisions

Revision ID: 8544272f42bf
Revises: 
Create Date: 2022-10-25 09:43:53.785954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8544272f42bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_signup_id'), 'signup', ['id'], unique=False)
    op.create_table('users_blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_blacklisted_tokens_id'), 'users_blacklisted_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_blacklisted_tokens_id'), table_name='users_blacklisted_tokens')
    op.drop_table('users_blacklisted_tokens')
    op.drop_index(op.f('ix_signup_id'), table_name='signup')
    op.drop_table('signup')
    # ### end Alembic commands ###
